set ::env(PDK) "sky130A"
set ::env(PDKPATH) "/home/briandeniz/.volare/sky130A"
set ::env(STD_CELL_LIBRARY) "sky130_fd_sc_hd"
set ::env(SCLPATH) "/home/briandeniz/.volare/sky130A/sky130_fd_sc_hd"
set ::env(DESIGN_DIR) "/openlane/designs/TopCPU"
set ::env(//) "Technology-Specific Configs"
set ::env(DESIGN_NAME) "TopCPU"
set ::env(VERILOG_FILES) "/openlane/designs/TopCPU/src/TopCPU.v /openlane/designs/TopCPU/src/InstructionMemory.v /openlane/designs/TopCPU/src/RegisterFile.v /openlane/designs/TopCPU/src/InstructionDecoder.v /openlane/designs/TopCPU/src/ALU.v"
set ::env(CLOCK_PERIOD) "10"
set ::env(CLOCK_PORT) "clk"
set ::env(PNR_SDC_FILE) "/openlane/designs/TopCPU/src/TopCPU.sdc"
set ::env(SIGNOFF_SDC_FILE) "/openlane/designs/TopCPU/src/TopCPU.sdc"
set ::env(PL_RANDOM_GLB_PLACEMENT) "0"
set ::env(FP_SIZING) "absolute"
set ::env(DIE_AREA) "0 0 1500 1800"
set ::env(PL_TARGET_DENSITY) "0.2"
set ::env(FP_CORE_UTIL) "0.3"
set ::env(FP_PDN_AUTO_ADJUST) "1"
set ::env(FP_PDN_VPITCH) "30"
set ::env(FP_PDN_HPITCH) "30"
set ::env(FP_PDN_VOFFSET) "5"
set ::env(FP_PDN_HOFFSET) "5"
set ::env(GRT_REPAIR_ANTENNAS) "1"
set ::env(DIODE_ON_PORTS) "both"
set ::env(RUN_HEURISTIC_DIODE_INSERTION) "1"
set ::env(FP_PIN_ORDER_CFG) "/openlane/designs/TopCPU/pin_order.cfg"
